apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: {{ .Values.ingress.port }}
      targetPort: {{ .Values.ingress.port }}  
  type: ClusterIP
