apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGODB_SERVICE: "{{ .Values.config.mongodb.service }}"
  MONGODB_PORT: "{{ .Values.config.mongodb.port }}"
  MONGODB_DATABASE: "{{ .Values.config.mongodb.database }}"
