services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./db/init.js:/docker-entrypoint-initdb.d/init.js:ro

  nodejs:
    build:
      context: ./backend
    container_name: nodejs
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventory

volumes:
  mongo_data:
