apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.service.mongodb.port }}
      targetPort: {{ .Values.service.mongodb.port }}
