apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - host: {{ .Values.ingress.appDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: {{ .Values.ingress.port }}
