apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    {{- include "apple-basket.mongodb.labels" . | nindent 4 }}
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
